name: A workflow for my Hello World files
on: push
jobs:
  build:
    name: Hello world Docker action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lsa
        run: ls -a
      - name: pwd
        run: pwd
      - name: HOME
        run: echo $HOME
     #- uses: ./action-b_docker
