name: A workflow for my Hello World files
on: push
jobs:
  build:
    name: Hello world Docker action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: playground
      - uses: ./action-b_docker
